// Generated by https://quicktype.io

export interface Search {
  [x: string]: any;
  searchType:   Type;
  expression:   string;
  results:      Result[];
  errorMessage: string;
}

export interface Result {
  id:          string;
  resultType:  Type;
  image:       string;
  title:       string;
  description: string;
}

export enum Type {
  Title = "Title",
}
